# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=test_user
ENV POSTGRES_PASSWORD=test_password
ENV POSTGRES_DB=content

# Copy initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/
COPY content.json /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432